void configure_clock(void) {
    /* Enable OSC32K */
    OSC32KCTRL->XOSC32K.reg = OSC32KCTRL_XOSC32K_ENABLE | OSC32KCTRL_XOSC32K_EN32K;
    while (!(OSC32KCTRL->STATUS.reg & OSC32KCTRL_STATUS_XOSC32KRDY));

    /* Set DFLL48M in closed-loop mode using OSC32K */
    GCLK->PCHCTRL[OSCCTRL_GCLK_ID_DFLL48].reg = GCLK_PCHCTRL_GEN_GCLK1 | GCLK_PCHCTRL_CHEN;
    while (!(GCLK->PCHCTRL[OSCCTRL_GCLK_ID_DFLL48].reg & GCLK_PCHCTRL_CHEN));

    OSCCTRL->DFLLCTRLA.reg = 0;  // Disable DFLL before configuration
    while (OSCCTRL->DFLLSYNC.bit.ENABLE);

    OSCCTRL->DFLLCTRLB.reg = OSCCTRL_DFLLCTRLB_MODE; // Closed-loop mode
    OSCCTRL->DFLLMUL.reg = OSCCTRL_DFLLMUL_CSTEP(31) | OSCCTRL_DFLLMUL_FSTEP(511) | OSCCTRL_DFLLMUL_MUL(1465);

    OSCCTRL->DFLLCTRLA.reg = OSCCTRL_DFLLCTRLA_ENABLE;
    while (!OSCCTRL->STATUS.bit.DFLLRDY);

    /* Set DFLL as the main clock source */
    GCLK->GENCTRL[0].reg = GCLK_GENCTRL_SRC_DFLL | GCLK_GENCTRL_GENEN;
    while (GCLK->SYNCBUSY.bit.GENCTRL0);
}
